### ISSUE TITLE
Unexpected :: in use item?

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#1]
I have a lalrpop file that begins with:
```rust
use crate::{
	grammar::{
		lexer,
		lexer::TokLoc,
		ast::*,
	},
};
```

Aside the wrong highlighting on the `grammar` word here, I get an error on the first `:` after `crate`, saying: `LALRPOP.SEMICOLON expected, got ':'`

**Comment by Mcat12** [comment]
Thanks for trying out the plugin! I thought this kind of import might have issues... I'm currently working on making the import section of the grammar file act like embedded Rust code, which should also fix this issue.

**Comment by Mcat12** [comment]
This should be fixed in the latest commit, https://github.com/Mcat12/intellij-lalrpop/commit/58083687d42dd7443fecbad34de7571e768de3b3
