### ISSUE TITLE
Inject Rust into nonterminal types

### ISSUE THREAD

**Issue by Mcat12** [Mcat12/intellij-lalrpop#12]
Idea: take something like
```
Comma<T>: Vec<T> {
    // ...
}
```
and inject Rust into the type using something like:
```rust
type __intellij_lalrpop_Comma<T> = Vec<T>;
```

**Comment by dblanovschi** [comment]
Does the name really matter? If not I think it would be a better idea to inject that for all `type_ref`s

**Comment by Mcat12** [comment]
I don't think the name of the type alias matters, but it probably should be different enough that it won't be referenced by the user. Also, each injection site should be independent of each other, so names shouldn't clash anyways.

That's a good idea, injecting for all non-recursive type_refs.

**Comment by dblanovschi** [comment]
There's one small catch here:
```rust
Nonterminal<Rule>: Box<Rule> = {/*...*/};
```

Trying to rename "Rule" from the injection leads to 
![image](https://user-images.githubusercontent.com/39565527/102888494-978c4180-4461-11eb-965c-e4f02f362dab.png)
