### ISSUE TITLE
When return type of a nonterminal is unspecified, the plugin uses the `toString()` on the nonterminal name which leads to "LpNonterminalNameImpl({debug name})"

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#16]
Issue is [here](https://github.com/Mcat12/intellij-lalrpop/blob/master/src/main/kotlin/com/mdrobnak/lalrpop/injectors/LpRustActionCodeInjector.kt#L31), when `getTypeRef()` returned `null`

**Comment by Mcat12** [comment]
This definitely should be solved, but if there's action code then lalrpop can't infer the type, so it must be specified. This case is then a compile time lalrpop error.

**Comment by Mcat12** [comment]
I think this is solved as of the above commit (or if that didn't catch it, then #17)
