### ISSUE TITLE
Support fallible actions

### ISSUE THREAD

**Issue by Schyrsivochter** [Mcat12/intellij-lalrpop#28]
Currently, when using [fallible actions](http://lalrpop.github.io/lalrpop/tutorial/007_fallible_actions.html), the plugin erroneously treats the action code as if returning the nonterminal’s return type directly, rather than a `Result`. This leads to perfectly valid code being marked as ‘mismatched types’.

Adjust the Rust code injection so that action code of a rule marked with `=>?` rather than `=>` returns not `T`, but `Result<T, Error>` where `Error` is the grammar’s user error type, which is `&'static str` by default but can be overriden (`extern { type Error = ... }`)

**Comment by Schyrsivochter** [comment]
hold on, I’m stupid. this was already implemented in #24 the other day

**Comment by dblanovschi** [comment]
> which is `&'static str` by default

Wait I got this bit wrong, and assumed it was `()` :grimacing:

**Comment by Mcat12** [comment]
It looks like the default changed in 0.14 from `()` to `&'static str`:
https://github.com/lalrpop/lalrpop/blob/6fd067fb4a14243b2dc396c6d4487958460e01e4/RELEASES.md#version-014

**Comment by dblanovschi** [comment]
It's sad the book isn't kept up to date. I used the last snippet in http://lalrpop.github.io/lalrpop/tutorial/002_paren_numbers.html to get the defaults.
