### ISSUE TITLE
Show type hints for inferred nonterminal types

### ISSUE THREAD

**Issue by Mcat12** [Mcat12/intellij-lalrpop#34]
When a nonterminal does not explicitly state its type, show the inferred type as a type hint.

Similar to how type hints are shown in Rust code:
![image](https://user-images.githubusercontent.com/4417660/103925375-72e0cc80-50e5-11eb-865d-79b22d465251.png)

Do something similar for nonterminals:
```
// This has the type Vec<T>
Comma<T> = Deliminate<T, ",">;
```

**Comment by dblanovschi** [comment]
I actually wanted to do this. The rust plugin has [some code available as public API](https://github.com/intellij-rust/intellij-rust/tree/master/src/main/kotlin/org/rust/ide/presentation), which would also add the references you could navigate, at the expense of showing `?` / `&?` / `&mut ?` when it cannot find something.

**Comment by Mcat12** [comment]
You can surely work on this; I made the issue to track the idea (I didn't intend to claim the assignment outright).

**Comment by dblanovschi** [comment]
Wow... Was looking at the wrong thing the whole time. No wonder it wasn't working :sweat_smile:

**Comment by dblanovschi** [comment]
Got it to work:

![image](https://user-images.githubusercontent.com/39565527/103950000-cafaeb80-5144-11eb-8797-cb5fa3fd464c.png)

**Comment by dblanovschi** [comment]
Might be a little bit overkill but I added the inlay for selected symbols in alternatives too, here's how the same code as above looks now:

![image](https://user-images.githubusercontent.com/39565527/104027758-861c9680-51d0-11eb-8283-3e5724822387.png)

@Mcat12 thoughts?

Maybe also would be a good idea to put this behind an option in the settings because it looks like too much.

**Comment by Mcat12** [comment]
I think it might be better to have the symbol types only be shown when you hover over them (like documentation).

**Comment by dblanovschi** [comment]
Uhh I added the options already :disappointed: 
![image](https://user-images.githubusercontent.com/39565527/104037935-88d1b880-51dd-11eb-90c8-d9c8b18786d7.png)

**Comment by Mcat12** [comment]
I'm not opposed to it also being an option :)

**Comment by dblanovschi** [comment]
I think the way the rust plugin does something similar is through [the `elementDescriptionProvider` EP](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/META-INF/rust-core.xml#L244), offering that data on hover
