### ISSUE TITLE
have the plugin uploaded to intelliJ Marketplace?

### ISSUE THREAD

**Issue by Kilerd** [Mcat12/intellij-lalrpop#7]

**Comment by Mcat12** [comment]
Thanks for opening this issue! I do plan on uploading the plugin to the marketplace but was trying to make it a bit more usable. Maybe now it's time to upload an initial version.

**Comment by Kilerd** [comment]
I think the syntax highlight has been a super good improvement for writing `lalrpop` in IntelliJ. and there are also other useful features that you DID implement. 
An alpha or pre-release version should be released to IntelliJ marketplace or just package it into Github release, in that way, those who are interested in this plugin can try and test the plugin for you, and more feedback or issue would be created which can make the plugin be better consequently.

**Comment by Mcat12** [comment]
The plugin has been submitted to the plugin repository: https://plugins.jetbrains.com/plugin/15229-lalrpop

It's pending approval before it can be installed.

**Comment by Mcat12** [comment]
The plugin is now live!

**Comment by Kilerd** [comment]
awesome!
