### ISSUE TITLE
Other bugs in the grammar

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#8]
I tried importing [gluon's lalrpop grammar](https://github.com/gluon-lang/gluon/blob/master/parser/src/grammar.lalrpop) and found out that:
1. `'_` is not recognized as a lifetime ([`{Id}`](https://github.com/Mcat12/intellij-lalrpop/blob/master/src/main/grammars/LalrpopLexer.flex#L49) doesn't match `_`)
2. The `where` element, even though it is defined, it is never matched in the lexer.
3. The `forall` rule doesn't match nothing(it always expects a `for` in the `grammar_where_clause` rule). This can be fixed with:
```diff
- forall ::= FOR LESSTHAN <<comma type_param>> GREATERTHAN |
+ forall ::= (FOR LESSTHAN <<comma type_param>> GREATERTHAN)?
```
Or
```diff
- forall ::= FOR LESSTHAN <<comma type_param>> GREATERTHAN |
+ forall ::= FOR LESSTHAN <<comma type_param>> GREATERTHAN | ()
```

**Comment by Mcat12** [comment]
Thanks! If you want, feel free to open an PR, otherwise I'll work on this when I get a chance.
